#!/usr/bin/env python


import sys
import os
import eventlet
import socket
import logging
from config import config
from status import STATUS_CODES
from routing import ROUTES
from log import log
from core.server import handle
eventlet.monkey_patch()


def main():
    try:
        eventlet.serve(eventlet.listen((config.get("HOST"), int(config.get("PORT")))), handle,
                       concurrency=int(config.get("MAX_CONNECTIONS")))
    except socket.error as e:
        log.warn(e)
        eventlet.StopServer()
        sys.exit(0)
    except (SystemExit, KeyboardInterrupt):
        log.info("Stopping Asynchronous Python HTTP Daemon ...")
        sys.exit(os.EX_OK)


if __name__ == "__main__":
    log.info("Starting Asynchronous Python HTTP Daemon ... ")
    main()
