#!/usr/bin/env python


import sys
import os
import eventlet
import socket
import threading
from config import config
from log import log
from core.server import Server
from core.listener import s, pool
from core.defaults import *
eventlet.monkey_patch()


def main():
    while True:
        try:
            server = Server()
            sock, addr = s.accept()
            pool.spawn_n(server.handle, sock, addr)
        except socket.error as e:
            log.warn(e)
            eventlet.StopServer()
            sys.exit(0)
        except (SystemExit, KeyboardInterrupt):
            log.info("Stopping Liasis ...")
            sys.exit(os.EX_OK)


if __name__ == "__main__":
    log.info("Starting Liasis ... ")
    main()
